In [1]:
print('Hello')

Hello


In [2]:
import numpy as np

In [3]:
num = np.array([56,33,12,78,65,28,53,18])

In [4]:
num

array([56, 33, 12, 78, 65, 28, 53, 18])

In [5]:
num.dtype

dtype('int64')

In [6]:
x = 646758745985462345696856753657876534754
x

646758745985462345696856753657876534754

In [7]:
num = np.array([56,33,12,78,65,28,53,18], dtype=np.int8)

In [8]:
num

array([56, 33, 12, 78, 65, 28, 53, 18], dtype=int8)

In [9]:
M = np.array([[4,5,6],[8,7,9],[1,2,0]])

In [10]:
M

array([[4, 5, 6],
       [8, 7, 9],
       [1, 2, 0]])

In [11]:
M.shape

(3, 3)

In [12]:
M.max()

9

In [13]:
num

array([56, 33, 12, 78, 65, 28, 53, 18], dtype=int8)

In [14]:
num * 2

array([ 112,   66,   24, -100, -126,   56,  106,   36], dtype=int8)

In [15]:
num / 5 + 7.8

array([19. , 14.4, 10.2, 23.4, 20.8, 13.4, 18.4, 11.4])

In [16]:
num % 2 == 0

array([ True, False,  True,  True, False,  True, False,  True])

In [17]:
num[num % 2 == 0]

array([56, 12, 78, 28, 18], dtype=int8)